name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check *.ts

      - name: Run tests
        run: deno task test

      - name: Verify examples
        run: |
          chmod +x example.ts
          ./example.ts tool echo "CI Test"
          ./example.ts resource config
